#TODO: Change version
version: 'v0.0.1.{build}'

environment:
  matrix: 
  ##### msvc 2013 ########
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013"
    TOOLCHAIN_VERSION: 12
    BUILD_ARCH: x86
    BUILD_SHARED_LIBS: ON
    
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 12 2013 Win64"
    TOOLCHAIN_VERSION: 12
    BUILD_ARCH: x64
    BUILD_SHARED_LIBS: ON

  ##### msvc 2015 ########
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x86
    BUILD_SHARED_LIBS: ON

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x64
    BUILD_SHARED_LIBS: ON
  
  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015"
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x86
    BUILD_SHARED_LIBS: OFF

  - BUILD_TARGERT: windows_msvc
    GENERATORS: "Visual Studio 14 2015 Win64"
    TOOLCHAIN_VERSION: 14
    BUILD_ARCH: x64
    BUILD_SHARED_LIBS: OFF

  ##### msvc 2017 ########
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 14 2015"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    BUILD_SHARED_LIBS: OFF
        
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 14 2015 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x64
    BUILD_SHARED_LIBS: OFF
    
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 14 2015 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x86
    BUILD_SHARED_LIBS: ON
  
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATORS: "Visual Studio 14 2015 Win64"
    BUILD_TARGERT: windows_msvc
    TOOLCHAIN_VERSION: 15
    BUILD_ARCH: x64
    BUILD_SHARED_LIBS: ON
  
  ##### mingw ########
  - BUILD_TARGERT: windows_mingw
    GENERATORS: "MSYS Makefiles"
    TOOLCHAIN_VERSION: 492_32
    BUILD_ARCH: x86
    BUILD_SHARED_LIBS: ON

  - BUILD_TARGERT: windows_mingw
    GENERATORS: "MSYS Makefiles"
    TOOLCHAIN_VERSION: 530_32
    BUILD_ARCH: x86
    BUILD_SHARED_LIBS: ON
    
  - BUILD_TARGERT: windows_mingw
    GENERATORS: "MSYS Makefiles"
    TOOLCHAIN_VERSION: 730_64
    BUILD_ARCH: x64
    BUILD_SHARED_LIBS: ON
  
  - BUILD_TARGERT: windows_mingw
    GENERATORS: "MSYS Makefiles"
    TOOLCHAIN_VERSION: 730_64
    BUILD_ARCH: x64
    BUILD_SHARED_LIBS: OFF
    
matrix:
  fast_finish: false

init:
  - set BUILD_VERSION=%APPVEYOR_BUILD_VERSION%
  - set varch=%BUILD_ARCH%
  - if "%BUILD_ARCH%" == "x64" set varch=amd64
  - if "%BUILD_TARGERT%" == "windows_msvc" if %TOOLCHAIN_VERSION% LSS 15 (call "C:\Program Files (x86)\Microsoft Visual Studio %TOOLCHAIN_VERSION%.0\VC\vcvarsall.bat" %varch%) else (call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %varch%)  
  - echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
  - echo PROCESSOR_IDENTIFIER=%PROCESSOR_IDENTIFIER%
  - del C:\msys64\usr\bin\link.exe

install:
  - C:\msys64\autorebase.bat
  - if "%BUILD_TARGERT%" == "windows_mingw" set MSYSTEM=MINGW32  #设置编译系统为MINGW32

before_build:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - if "%BUILD_TARGERT%" == "android" C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build-install-tools-windows.sh

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\msys64\usr\bin\bash.exe %APPVEYOR_BUILD_FOLDER%\ci\build.sh

artifacts:
  - path: build_$(BUILD_TARGERT)\install
    name: SeetaFace_$(BUILD_TARGERT)$(TOOLCHAIN_VERSION)_$(BUILD_ARCH)
    type: zip

test: off

#See:https://www.appveyor.com/docs/deployment/github/
deploy:
  - provider: GitHub
    #release: Seeta$(appveyor_build_version)
    description: 'Release Seeta $(APPVEYOR_REPO_TAG_NAME) on windows'
    #token : https://github.com/settings/tokens
    #password encrypt: https://ci.appveyor.com/tools/encrypt
    auth_token:
      secure: OiAMIB7yqZ/SGuSgTU+N5LnPW2iUZcWCaQEyqDLmR/4ySc5A7zeUxkSh580cIO7F
    #draft: true
    #prerelease: true
    on:
      BUILD_SHARED_LIBS: ON
      appveyor_repo_tag: true        # deploy on tag push only
